env:
  es2022: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
ignorePatterns:
  - '**/dist/*'
  - '**/build/*'
rules:
  'prettier/prettier': error
