extends:
  - 'plugin:react/recommended'
  - './.eslintrc.yml'
plugins:
  - 'react-hooks'
rules:
  'react-hooks/rules-of-hooks': error
  'react-hooks/exhaustive-deps': warn
  'react/prop-types': off
settings:
  react:
    pragma: React
    version: detect
